# Generated by Django 2.1.1 on 2020-06-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200611_0343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='image_url',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
