# Generated by Django 2.2.13 on 2020-06-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200611_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
