# Generated by Django 2.2.13 on 2020-06-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200612_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='rest_id',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
    ]
